# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4935986749977896d4d16038ad22baed2fc81e87e197b23df61c193843a029e877ee89e518ecb1887f15dd6fb6fc126fcd8f9d4c2dca06a0f542a40d50a36e06

test:
  secret_key_base: 20daf90cbfe9245871412239015f2b7823f30437584b6823f0da9aa767159cf203c950c48362061f766818754c48900d7f2123df4498c36c2c5a6b25fcda9593

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
